# Site settings
title: Michael SanAngelo's CV 
description: jms1989's CV
favicon: /assets/img/avatar.JPG
url: http://me.thelonegeek.net/
baseurl: 
rss_url: /pages/atom.xml
google_analytics: 
downloadpdf: /Joseph-SanAngelo-Resume.pdf

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Michael SanAngelo
  title: Computer Technician
  address: Bossier City, Louisiana, USA
  email: jms@thelonegeek.net
  link: http://me.thelonegeek.net
  weibo:
  github: jms1989
  linkedin: michael-sanangelo
#  twitter: 
  gavatar: /assets/img/avatar.JPG
#  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Jet Ski Haven
      location: Shreveport, LA
      title: Data Entry
      started: 2014
      duration: (2014 - 2014)
      description: <ul class="list-unstyled"><li>Displayed and priced merchandise, adjusted products on shelves and build in-store displays.</li><li>Provided electronic customer support and knowledge of merchandise location to customers.</li><li>Cleaned and organized shopping carts and store facility to prepare for customer satisfaction.</li><li>Unload merchandise daily.</li></ul>
    - work2:
      company: Freds, Inc
      location: Bossier City, LA
      title: Stocker
      started: 2008
      duration: (2008 - 2013)
      description: <ul class="list-unstyled"><li>Pull data from related websites for product entry (including product description, images, categories, etc.)</li><li>Categorize product listing by part types.</li><li>Prepare or organize online storefront marketing material, including product descriptions or subject lines, optimizing content to search engine criteria.</li></ul>
#    - work3:
#      company: 
#      location:
#      title: 
#      started: 
#      duration: 
#      description: 
  educationHistory:
    - education1:
      organization: Remington College
      location: Shreveport, LA
      degree: Electronic Technology
      major: 
      started: 2012
      duration: ( 2012 - 2013 )
      description: Crash course in electronics. <br/><p style="font-weight:bold;">Coursework</p><ul><li> Computer Hardware/Software</li><li>DC/AC Fundamentals</li><li>Cables and Cabling</li><li>Low Voltage Systems</li><li>Residential Networking</li></ul>
  languages:
    - language1:
      name: English
      proficiency: Native
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 60%
    - skill2:
      name: Bootstrap
      percentage: 40%
    - skill3:
      name: Javascript
      percentage: 10%
#    - skill4:
#      name: 
#      percentage: 0%
#    - skill5:
#      name: 
#      percentage: 0%
  electronicSkills:
    - skill1:
      name: Computer Builder
      percentage: 80%
    - skill2:
      name: Home Network Admin
      percentage: 80%
    - skill3:
      name: Soldering
      percentage: 50%

